#!/usr/bin/env bash
#
# Host-side part of the php-fpm stack: the /usr/local/bin/php shim.
#
# `php` on the host must mean "PHP 5.6 in a container": there is no modern php
# on the machine and there must not be one, while the sites' tooling (composer,
# migrations) calls exactly `php`. The shim joins the same network as the sites,
# so DBMS containers are reachable from it by name.
#
# It lives in the stack rather than in the platform: the platform is not
# required to know what PHP is. It is called from platform/bin/host-setup.sh
# because this file exists here.

set -euo pipefail

CHECK_ONLY=0
[ "${1:-}" = "--check" ] && CHECK_ONLY=1

# shellcheck source=platform/lib/lib-env.sh
. "${ROOT_DIR:?}/platform/lib/lib-env.sh"
ENV_VARS=(); env_load_files "$ROOT_DIR/.env" "$ROOT_DIR/stacks/php-fpm/.env"

VHOSTS="$(env_get Platform_Vhosts_Dir)"
NET="$(env_get Platform_Network)"
SHIM=/usr/local/bin/php

[ -n "$VHOSTS" ] && [ -n "$NET" ] || {
  echo "[FAIL] cannot build the shim: .env has no Platform_Vhosts_Dir and/or Platform_Network"; exit 1; }

render() {
  cat <<INNER
#!/bin/bash
# GENERATED by stacks/php-fpm/scripts/host-setup.sh -- edits are overwritten.
docker run -it --rm \\
    -e HOME="\$HOME" \\
    -u \$(id -u):\$(id -g) \\
    -v "\$HOME":"\$HOME" \\
    -v "\$PWD":"\$PWD" \\
    -v ${VHOSTS}:${VHOSTS} \\
    --network ${NET} \\
    -w "\$PWD" \\
    php5.6-fpm \\
    php5 "\$@"
exit \$?
INNER
}

if [ -f "$SHIM" ] && [ "$(cat "$SHIM")" = "$(render)" ]; then
  echo "[ok] $SHIM is in place and up to date"
elif [ "$CHECK_ONLY" -eq 1 ]; then
  echo "[FAIL] $SHIM is missing or has drifted from .env -- sudo ./host-setup"; exit 1
else
  render > "$SHIM"; chmod +x "$SHIM"
  echo "[ok] $SHIM written"
fi
