#!/bin/bash

# Creates databases and users in the shared postgres according to
# databases.yaml.
#
# That file is GENERATED by scripts/stack.sh from the <Prefix>_* keys in
# stacks/*/stack.conf, i.e. ultimately from the stacks' own .env files. Nobody
# edits it by hand: an edit survives exactly until the next `stack.sh sync`.
#
# Idempotent: existing users and databases are not recreated.

set -uo pipefail

echo "Waiting for PostgreSQL to become ready..."
until pg_isready -h postgres -U "$POSTGRES_USER"; do
  sleep 1
done
echo "PostgreSQL is ready. Reading the YAML..."

if [ ! -s /config/databases.yaml ]; then
  echo "Error: /config/databases.yaml is empty or missing." >&2
  echo "  It is generated by: ./scripts/stack.sh sync" >&2
  exit 1
fi

export PGPASSWORD="$POSTGRES_PASSWORD"
problems=0

# yq turns every array element into compact one-line JSON, and it can also read
# dotted values back out of those mini-JSON lines.
#
# Deliberately not `| while`: in a subshell the loop body would lose the
# problems counter, and the script would exit zero with divergences found.
while read -r row; do
    [ -n "$row" ] || continue
    DB_NAME=$(echo "$row" | yq e '.db' -)
    DB_USER=$(echo "$row" | yq e '.user' -)
    DB_PASS=$(echo "$row" | yq e '.password' -)
    # The key is 'dump', not 'dump_file': the generator writes the key name in
    # lower case without the prefix (Postgres_Dump -> dump), and the other
    # spelling here would mean the seed silently never lands -- the database is
    # created, the schema is empty, the application starts on it and fails at
    # runtime.
    DUMP_FILE=$(echo "$row" | yq e '.dump // ""' -)

    # 1. The user.
    USER_EXISTS=$(psql -h postgres -U "$POSTGRES_USER" -d postgres -tAc \
      "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'")
    if [ "$USER_EXISTS" != "1" ]; then
        echo "--> Creating user: $DB_USER"
        psql -h postgres -U "$POSTGRES_USER" -d postgres \
          -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';"
    else
        # The user already exists, so the password in the database was not set
        # by us and we do not know whether it matches the declared one. We test
        # it with a trial connection.
        #
        # ALTER USER is deliberately NOT done here: a password changed by hand
        # in psql and not written into the stack's .env would be silently
        # overwritten on the next `up -d`. The worst kind of surprise is the
        # quiet one.
        #
        # Staying silent is not an option either: the divergence shows up as
        # `P1000 / password authentication failed` in the application's log
        # hours after startup, and tying that back to db-initializer is hard by
        # then.
        if ! PGPASSWORD="$DB_PASS" psql -h postgres -U "$DB_USER" -d postgres \
             -tAc 'SELECT 1' >/dev/null 2>&1; then
            echo "--> [ERROR] the password of user '$DB_USER' in the database does NOT match the declared one." >&2
            echo "            Declaration: <Prefix>_Password in the stack's stack.conf," >&2
            echo "            the value    in stacks/<stack>/.env." >&2
            echo "            There are two ways to fix it:" >&2
            echo "              1) write the password the database has into .env;" >&2
            echo "              2) change the password in the database to the declared one:" >&2
            echo "                 docker exec -it postgres psql -U \$POSTGRES_USER -c \\\\" >&2
            echo "                   \"ALTER USER $DB_USER WITH PASSWORD '<new>';\"" >&2
            echo "            Then ./scripts/stack.sh sync && ./docker-compose.sh up -d db-initializer" >&2
            problems=$((problems + 1))
            continue
        fi
    fi

    # 2. The database.
    DB_EXISTS=$(psql -h postgres -U "$POSTGRES_USER" -d postgres -tAc \
      "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'")
    if [ "$DB_EXISTS" != "1" ]; then
        echo "--> Creating database: $DB_NAME"
        psql -h postgres -U "$POSTGRES_USER" -d postgres \
          -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;"
        psql -h postgres -U "$POSTGRES_USER" -d postgres \
          -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"

        # The dump is loaded ONLY when the database is created. Otherwise every
        # `up -d` would pour the seed over live data.
        if [ -n "$DUMP_FILE" ] && [ "$DUMP_FILE" != "null" ] && [ -f "/dumps/$DUMP_FILE" ]; then
            echo "--> [!] Loading dump $DUMP_FILE into database $DB_NAME..."
            psql -h postgres -U "$POSTGRES_USER" -d "$DB_NAME" -f "/dumps/$DUMP_FILE"
            echo "--> Dump restored."
        fi
    else
        echo " Database $DB_NAME already exists. Skipping."
    fi
done < <(yq e '.[] | @json' /config/databases.yaml)

if [ "$problems" -gt 0 ]; then
  echo >&2
  echo "Password divergences: $problems. The databases concerned were left untouched." >&2
  exit 1
fi

echo "All databases are in sync."
