server {
	listen		80;
	server_name	secrets.12devs.info;

	client_max_body_size 32m;

	include		/etc/nginx/snippets/letsencrypt.conf;

	include		/etc/nginx/snippets/redirect-to-https.conf;
}



server {
	listen		443 ssl;
	http2		on;
	server_name	secrets.12devs.info;

	access_log	/var/log/nginx/secrets.12devs.info-access;
	error_log	/var/log/nginx/secrets.12devs.info-error;


	include			/etc/nginx/snippets/ssl-params.conf;
	ssl_certificate		/etc/nginx/certs/secrets.12devs.info-fullchain.crt;
	ssl_certificate_key	/etc/nginx/certs/secrets.12devs.info.key;

	include		/etc/nginx/snippets/letsencrypt.conf;

	location / {
		proxy_pass http://vault:8200;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
	}

}