server {
	listen		80;
	server_name	design.12devs.com;

	client_max_body_size 32m;

	include		/etc/nginx/snippets/letsencrypt.conf;

	include		/etc/nginx/snippets/redirect-to-https.conf;
}



server {
	listen		443 ssl;
	http2		on;
	server_name	design.12devs.com;

	access_log	/var/log/nginx/design.12devs.com-access;
	error_log	/var/log/nginx/design.12devs.com-error;

	root		/var/www/vhosts/design.12devs.com/public;
	index		index.html;

	include			/etc/nginx/snippets/ssl-params.conf;
	ssl_certificate		/etc/nginx/certs/design.12devs.com-fullchain.crt;
	ssl_certificate_key	/etc/nginx/certs/design.12devs.com.key;

	include		/etc/nginx/snippets/letsencrypt.conf;

	location / {
		root	/var/www/vhosts/design.12devs.com/public;
		index	index.html;
	}

	location ~* ^.+.(jpg|jpeg|gif|css|png|js|ico)$ {
		access_log	off;
		expires	30d;
	}
}
