#!/usr/bin/env bash
#
# Host-side part of the mysql stack: the config for the _db toolkit, if the
# machine has one.
#
# _db is a set of manual database tools (dbquery, dbconsole, dbdump). Its
# db.conf used to appear as a side effect of provisioning MySQL; without this
# step dbquery.sh would silently read empty values.
#
# The toolkit is optional: a machine without a _db/ directory is skipped
# silently rather than failing.

set -euo pipefail

CHECK_ONLY=0
[ "${1:-}" = "--check" ] && CHECK_ONLY=1

DB_DIR="${ROOT_DIR:?}/_db"
[ -d "$DB_DIR" ] || { echo "[ok] no _db/ directory -- the toolkit is not used on this machine"; exit 0; }

# shellcheck source=platform/lib/lib-env.sh
. "$ROOT_DIR/platform/lib/lib-env.sh"
ENV_VARS=(); env_load_files "$ROOT_DIR/.env" "$ROOT_DIR/stacks/mysql/.env"

PW="$(env_get Mysql_Root_Password)"
NET="$(env_get Platform_Network)"
[ -n "$PW" ] || { echo "[FAIL] stacks/mysql/.env has no Mysql_Root_Password"; exit 1; }

render() {
  cat <<INNER
# GENERATED by stacks/mysql/scripts/host-setup.sh from .env -- edits are overwritten.
DBNAME=mysql
DBUSER=root
DBPASS='${PW}'
DBHOST=localhost
DBDUMP=./dump.sql

DOCKER_MYSQLD_CONTAINER=mysqld
DOCKER_NETWORK=${NET}
DOCKER_COMPOSE_SERVICE=
INNER
}

if [ -f "$DB_DIR/db.conf" ] && [ "$(cat "$DB_DIR/db.conf")" = "$(render)" ]; then
  echo "[ok] _db/db.conf is up to date"
elif [ "$CHECK_ONLY" -eq 1 ]; then
  echo "[FAIL] _db/db.conf is missing or has drifted from .env -- sudo ./host-setup"; exit 1
else
  render > "$DB_DIR/db.conf"
  # It contains the shared DBMS root password.
  chmod 600 "$DB_DIR/db.conf"
  echo "[ok] _db/db.conf written"
fi
