#!/usr/bin/env bash

# Creates databases, users and their privileges in the shared MySQL according
# to databases.yaml.
#
# That file is GENERATED by platform/bin/stack.sh from the Mysql_* keys in
# stacks/*/stack.conf, i.e. ultimately from the stacks' own .env files. Nobody
# edits it by hand: an edit survives exactly until the next `stack.sh sync`.
#
# It is idempotent, and that is its main property: the container is one-shot
# but comes up on EVERY `up -d`. Existing users and databases are not
# recreated, and data is not touched.
#
# What it NEVER does:
#   * change the password of an existing user;
#   * revoke privileges that are not in the declaration;
#   * drop or overwrite an existing database.
# All of those are silent destructive actions; instead of doing them it prints
# the divergence and fails the run.

set -uo pipefail

MYSQL_HOST=mysqld

# The user is created EXACTLY as 'name'@'%'.
#
# In MySQL an account is a (user, host) pair, and 'app'@'%' and
# 'app'@'localhost' are two different records with different privileges and
# different passwords. Containers reach this host over the bridge network from
# random addresses, so the only form that works is '%'. Creating a second pair
# would give an account that half the connections land on -- with "Access
# denied" under a password that is provably correct.
USER_HOST='%'

echo "Waiting for MySQL to become ready..."
for _ in $(seq 1 60); do
  mysqladmin ping -h"$MYSQL_HOST" -uroot -p"$MYSQL_ROOT_PASSWORD" --silent >/dev/null 2>&1 && break
  sleep 1
done
mysqladmin ping -h"$MYSQL_HOST" -uroot -p"$MYSQL_ROOT_PASSWORD" --silent >/dev/null 2>&1 \
  || { echo "Error: MySQL did not come up within 60 seconds." >&2; exit 1; }
echo "MySQL is ready. Reading the YAML..."

if [ ! -s /config/databases.yaml ]; then
  echo "Error: /config/databases.yaml is empty or missing." >&2
  echo "  It is generated by: ./stack sync" >&2
  exit 1
fi

# The root password goes through MYSQL_PWD rather than an argument: anything in
# argv is visible in `ps` to every process in the container.
export MYSQL_PWD="$MYSQL_ROOT_PASSWORD"
root_q() { mysql -h"$MYSQL_HOST" -uroot -N -B -e "$1"; }

problems=0

# A MySQL string literal. Both the backslash and the quote are escaped -- a
# password can contain either, and a literal cut short on a special character
# either breaks the query or (worse) creates a user with a truncated password.
sql_str() { local v="$1"; v="${v//\\/\\\\}"; v="${v//\'/\\\'}"; printf "'%s'" "$v"; }

# Identifiers (database name, user name) are not quoted but VALIDATED.
# Backticks around a name save you from spaces but not from a name containing a
# backtick itself -- and the declaration comes from a .env that a human edits.
valid_ident() { [[ "$1" =~ ^[A-Za-z0-9_]+$ ]]; }

# The privileges declared by the stack: upper case, one per line.
norm_grants() {
  printf '%s' "$1" | tr ',' '\n' | tr 'a-z' 'A-Z' \
    | sed 's/^[[:space:]]*//; s/[[:space:]]*$//' | sed '/^$/d' | sort -u
}

# The privileges the user ACTUALLY has on this database.
#
# `SHOW GRANTS` returns lines like
#   GRANT SELECT, INSERT ON `db`.* TO 'u'@'%'
# plus the mandatory GRANT USAGE ON *.* -- that one means "the account exists",
# not a privilege, and it is left out of the comparison.
current_grants() {
  local user="$1" db="$2"
  root_q "SHOW GRANTS FOR $(sql_str "$user")@$(sql_str "$USER_HOST")" 2>/dev/null \
    | grep -F "ON \`${db}\`.*" \
    | sed -E 's/^GRANT (.*) ON .*/\1/' \
    | tr ',' '\n' | tr 'a-z' 'A-Z' \
    | sed 's/^[[:space:]]*//; s/[[:space:]]*$//' | sed '/^$/d' | sort -u
}

# Deliberately not `| while`: in a subshell the loop body would lose the
# problems counter, and the script would exit zero with divergences found.
while read -r row; do
    [ -n "$row" ] || continue
    DB_NAME=$(echo "$row"   | yq e '.db' -)
    DB_USER=$(echo "$row"   | yq e '.user' -)
    DB_PASS=$(echo "$row"   | yq e '.password' -)
    DB_GRANTS=$(echo "$row" | yq e '.grants // "SELECT,INSERT,UPDATE,DELETE"' -)
    # The key is 'dump', not 'dump_file': the generator writes the key name in
    # lower case without the prefix (Mysql_Dump -> dump), and the other spelling
    # here would mean the seed silently never lands -- the database is created,
    # the schema is empty, the application starts on it and fails at runtime.
    DUMP_FILE=$(echo "$row" | yq e '.dump // ""' -)

    if ! valid_ident "$DB_NAME" || ! valid_ident "$DB_USER"; then
        echo "--> [ERROR] database name '$DB_NAME' or user name '$DB_USER' contains invalid characters." >&2
        echo "            Letters, digits and underscore are allowed." >&2
        problems=$((problems + 1)); continue
    fi

    # 1. The user.
    USER_EXISTS=$(root_q "SELECT 1 FROM mysql.user WHERE User=$(sql_str "$DB_USER") AND Host=$(sql_str "$USER_HOST")")
    if [ "$USER_EXISTS" != "1" ]; then
        echo "--> Creating user: ${DB_USER}@${USER_HOST}"
        root_q "CREATE USER $(sql_str "$DB_USER")@$(sql_str "$USER_HOST") IDENTIFIED BY $(sql_str "$DB_PASS");" \
          || { echo "--> [ERROR] could not create user $DB_USER" >&2; problems=$((problems + 1)); continue; }
    else
        # The user already exists, so the password in the database was not set
        # by us and we do not know whether it matches the declared one. We test
        # it with a trial connection.
        #
        # SET PASSWORD is deliberately NOT done here: a password changed by hand
        # and not written into the stack's .env would be silently overwritten on
        # the next `up -d`. The worst kind of surprise is the quiet one.
        #
        # Staying silent is not an option either: the divergence shows up as
        # `Access denied for user` in the application's log hours after startup,
        # and tying that back to the initializer is hard by then.
        if ! MYSQL_PWD="$DB_PASS" mysql -h"$MYSQL_HOST" -u"$DB_USER" -N -B -e 'SELECT 1' >/dev/null 2>&1; then
            echo "--> [ERROR] the password of '${DB_USER}@${USER_HOST}' in the database does NOT match the declared one." >&2
            echo "            Declaration: <Prefix>_Password in the stack's stack.conf," >&2
            echo "            the value    in stacks/<stack>/.env." >&2
            echo "            There are two ways to fix it:" >&2
            echo "              1) write the password the database has into .env;" >&2
            echo "              2) change the password in the database to the declared one:" >&2
            echo "                 docker exec -it mysqld mysql -uroot -p -e \\" >&2
            echo "                   \"SET PASSWORD FOR '${DB_USER}'@'${USER_HOST}' = PASSWORD('<new>');\"" >&2
            echo "            Then ./stack sync && ./dc up -d mysql-initializer" >&2
            problems=$((problems + 1)); continue
        fi
    fi

    # 2. The database.
    DB_EXISTS=$(root_q "SELECT 1 FROM information_schema.SCHEMATA WHERE SCHEMA_NAME=$(sql_str "$DB_NAME")")
    if [ "$DB_EXISTS" != "1" ]; then
        # utf8, not utf8mb4, deliberately. In MySQL 5.5 the InnoDB index key
        # length limit is 767 bytes, and a VARCHAR(255) under utf8mb4
        # (255*4 = 1020) does not fit into an index: the application fails on
        # the migration, not on a query. A stack that needs utf8mb4 will have to
        # narrow such columns.
        echo "--> Creating database: $DB_NAME"
        root_q "CREATE DATABASE \`${DB_NAME}\` CHARACTER SET utf8 COLLATE utf8_general_ci;" \
          || { echo "--> [ERROR] could not create database $DB_NAME" >&2; problems=$((problems + 1)); continue; }

        # The dump is loaded ONLY when the database is created. Otherwise every
        # `up -d` would pour the seed over live data.
        if [ -n "$DUMP_FILE" ] && [ "$DUMP_FILE" != "null" ] && [ -f "/dumps/$DUMP_FILE" ]; then
            echo "--> [!] Loading dump $DUMP_FILE into database $DB_NAME..."
            mysql -h"$MYSQL_HOST" -uroot "$DB_NAME" < "/dumps/$DUMP_FILE" \
              || { echo "--> [ERROR] dump $DUMP_FILE failed to load" >&2; problems=$((problems + 1)); }
            echo "--> Dump restored."
        fi
    else
        echo " Database $DB_NAME already exists. Leaving it alone."
    fi

    # 3. Privileges.
    #
    # We grant what is missing and do NOT revoke what is extra. GRANT is
    # additive, so re-granting the declared set takes nothing away by itself --
    # whereas a silent REVOKE would remove a privilege granted by hand for a
    # specific job and break the application at a moment unrelated to it.
    #
    # But staying silent about the extras is not an option either: the point of
    # limited privileges is that the set is known. So a divergence is a loud
    # error with a ready-made command.
    want="$(norm_grants "$DB_GRANTS")"
    have="$(current_grants "$DB_USER" "$DB_NAME")"

    missing="$(comm -23 <(printf '%s\n' "$want") <(printf '%s\n' "$have"))"
    if [ -n "$missing" ]; then
        list="$(printf '%s' "$missing" | tr '\n' ',' | sed 's/,$//')"
        echo "--> Granting ${list} on ${DB_NAME} to ${DB_USER}@${USER_HOST}"
        root_q "GRANT ${list} ON \`${DB_NAME}\`.* TO $(sql_str "$DB_USER")@$(sql_str "$USER_HOST");" \
          || { echo "--> [ERROR] could not grant privileges on $DB_NAME" >&2; problems=$((problems + 1)); }
    fi

    extra="$(comm -13 <(printf '%s\n' "$want") <(printf '%s\n' "$have") | grep -vx 'USAGE')"
    if [ -n "$extra" ]; then
        list="$(printf '%s' "$extra" | tr '\n' ',' | sed 's/,$//')"
        echo "--> [ERROR] '${DB_USER}@${USER_HOST}' has privileges on ${DB_NAME} beyond the declared ones: ${list}" >&2
        echo "            We do not revoke them ourselves: a removed privilege breaks the" >&2
        echo "            application at a moment unrelated to it. Decide which is right:" >&2
        echo "              1) they are needed -- add them to the stack's <Prefix>_Grants and \`stack.sh sync\`;" >&2
        echo "              2) they are extra -- revoke them by hand:" >&2
        echo "                  docker exec -it mysqld mysql -uroot -p -e \\" >&2
        echo "                    \"REVOKE ${list} ON \\\`${DB_NAME}\\\`.* FROM '${DB_USER}'@'${USER_HOST}';\"" >&2
        problems=$((problems + 1))
    fi

done < <(yq e '.[] | @json' /config/databases.yaml)

if [ "$problems" -gt 0 ]; then
  echo >&2
  echo "Divergences: $problems. The databases concerned were left untouched." >&2
  exit 1
fi

echo "All databases and privileges are in sync."
