server {
	listen		80;
	server_name	www.12devs.by 12devs.by;

	include		/etc/nginx/snippets/letsencrypt.conf;

	location / {
		return  301     https://twelvedevs.com/;
	}
}



server {
	listen		443 ssl;
	listen		[::]:443 ssl;
	http2		on;
	server_name	www.12devs.by 12devs.by;

	include			/etc/nginx/snippets/ssl-params.conf;
	ssl_certificate		/etc/nginx/certs/12devs.by-fullchain.crt;
	ssl_certificate_key	/etc/nginx/certs/12devs.by.key;

	include		/etc/nginx/snippets/letsencrypt.conf;

	location / {
		return  301     https://twelvedevs.com/;
	}
}
